name: "Telegram Bot API"
description: "Self-hosted local instance of the Telegram Bot API server with proxy support"
url: "https://github.com/avbor/hassio-apps"
image: "ghcr.io/avbor/ha-telegram-bot-api/{arch}"
arch:
  - amd64
  - aarch64
version: "9.5"
slug: "telegram-bot-api"
apparmor: true
init: false
ingress: true
ingress_port: 8082
panel_icon: mdi:send-circle
panel_title: "Telegram Bot API Statistics"
panel_admin: true
ports:
  8081/tcp: null
  8082/tcp: null
startup: system
map:
  - media
options:
  log_level: 1
  stat_enabled: true
  proxy:
    prx_type: none
schema:
  api_id: str
  api_hash: password
  log_level: int(1,4)
  stat_enabled: bool
  proxy:
    prx_type: list(none|mtproto|socks5|http)
    prx_server: str?
    prx_port: port?
    prx_username: str?
    prx_password: password?
    prx_secret: password?
watchdog: tcp://[HOST]:[PORT:8081]
